import{i as y,a as L,S as x}from"./assets/vendor-5401a4b0.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const b=document.getElementById("search-form"),p=document.getElementById("gallery"),l=document.querySelector(".loader"),i=document.getElementById("load-more"),w="42189534-0458e72641624c0165f7139a5",d={messageColor:"#FFF",color:"#EF4040",position:"topRight",timeout:3e3},s={key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,q:"",page:1,per_page:15};b.addEventListener("submit",async function(e){e.preventDefault(),l.style.display="block";const a=e.target.elements.input.value;s.q=a,s.page=1;try{const o=await u();E(o)}catch{y.error({title:"Error",message:"An error occurred. Please try again later.",...d})}e.target.reset()});i.addEventListener("click",async function(){l.style.display="block",s.page++;try{const e=await u();g(e)}catch{y.error({title:"Error",message:"An error occurred. Please try again later.",...d})}});async function u(){try{return(await L.get("https://pixabay.com/api/",{params:s})).data}catch(e){throw new Error(e.response.status)}}function E(e){e.hits.length===0?(y.show({...d,message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),p.innerHTML!==""&&(p.innerHTML=""),i.style.display="none"):(s.page===1&&(p.innerHTML=""),g(e),e.totalHits<=s.page*s.per_page?i.style.display="none":i.style.display="block"),l.style.display="none"}function g(e){l.style.display="block";const a=e.hits.map(({largeImageURL:c,webformatURL:t,tags:r,likes:n,views:m,comments:f,downloads:h})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${c}'>
    <img class='gallery-image' src='${t}' alt='${r}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${n}</p>
<p><span>Views</span> ${m}</p>
<p><span>Comments</span> ${f}</p>
<p><span>Downloads</span> ${h}</p>
</div>
 </li>`).join("");p.insertAdjacentHTML("beforeend",a),l.style.display="none",s.page*15>=e.totalHits&&(i.style.display="none",y.show({...d,message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"})),new x(".gallery-link").refresh()}
//# sourceMappingURL=commonHelpers.js.map
