import{i as d,a as L,S as x}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const b=document.getElementById("search-form"),c=document.getElementById("gallery"),i=document.querySelector(".loader"),p=document.getElementById("load-more"),w="42189534-0458e72641624c0165f7139a5",y={messageColor:"#FFF",color:"#EF4040",position:"topRight",timeout:3e3},o={key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,q:"",page:1,per_page:15};b.addEventListener("submit",async function(t){t.preventDefault(),i.style.display="block";const s=t.target.elements.input.value;o.q=s,o.page=1;try{const a=await u();E(a)}catch{d.error({title:"Error",message:"An error occurred. Please try again later.",...y})}t.target.reset()});p.addEventListener("click",async function(){i.style.display="block",o.page++;try{const t=await u();g(t)}catch{d.error({title:"Error",message:"An error occurred. Please try again later.",...y})}});async function u(){try{return(await L.get("https://pixabay.com/api/",{params:o})).data}catch(t){throw new Error(t.response.status)}}function E(t){t.hits.length===0?(d.show({...y,message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),c.innerHTML!==""&&(c.innerHTML=""),p.style.display="none"):(o.page===1&&(c.innerHTML=""),g(t),p.style.display="block"),i.style.display="none"}function g(t){i.style.display="block";const s=t.hits.map(({largeImageURL:l,webformatURL:e,tags:r,likes:n,views:m,comments:f,downloads:h})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${l}'>
    <img class='gallery-image' src='${e}' alt='${r}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${n}</p>
<p><span>Views</span> ${m}</p>
<p><span>Comments</span> ${f}</p>
<p><span>Downloads</span> ${h}</p>
</div>
 </li>`).join("");c.insertAdjacentHTML("beforeend",s),i.style.display="none",o.page*15>=t.totalHits&&(p.style.display="none",d.show({...y,message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"})),new x(".gallery-link").refresh()}
//# sourceMappingURL=commonHelpers.js.map
