import{a as h,i as d,S as F}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const b=document.getElementById("search-form"),p=document.getElementById("gallery"),n=document.querySelector(".loader"),c=document.getElementById("load-more"),L="42189534-0458e72641624c0165f7139a5",i={key:L,image_type:"photo",orientation:"horizontal",safesearch:!0,q:"",page:1,per_page:15};b.addEventListener("submit",async function(e){e.preventDefault(),n.style.display="block";const r=e.target.elements.input.value;i.q=r,i.page=1;try{const o=await y();x(o)}catch(o){console.error(o)}e.target.reset()});c.addEventListener("click",async function(){n.style.display="block",i.page++;try{const e=await y();u(e)}catch(e){console.error(e)}});async function y(){try{return(await h.get("https://pixabay.com/api/",{params:i})).data}catch(e){throw new Error(e.response.status)}}function x(e){e.hits.length===0?(d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),p.innerHTML="",c.style.display="none"):(p.innerHTML="",u(e),c.style.display="block"),n.style.display="none"}function u(e){n.style.display="block";const r=e.hits.map(({largeImageURL:l,webformatURL:t,tags:s,likes:a,views:g,comments:m,downloads:f})=>`<li class='gallery-item'>
  <a class='gallery-link' href='${l}'>
    <img class='gallery-image' src='${t}' alt='${s}'/>
  </a>
<div class='container-app'>
<p><span>Likes</span> ${a}</p>
<p><span>Views</span> ${g}</p>
<p><span>Comments</span> ${m}</p>
<p><span>Downloads</span> ${f}</p>
</div>
 </li>`).join("");p.insertAdjacentHTML("beforeend",r),n.style.display="none",i.page*15>=e.totalHits&&(c.style.display="none",d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"})),new F(".gallery-link").refresh()}
//# sourceMappingURL=commonHelpers.js.map
